### ISSUE TITLE
Use of EcmaScript 6 features breaks polymer build

### ISSUE THREAD

**Issue by jhansmeyer** [telecomsante/tsante-mqtt#1]
For me the use of arrow functions and default function parameters in tsante-mqtt-subscriber.html and tsante-mqtt-publisher.html prevents a proper polymer build. This will also propably not work in IE 11.

this.parentElement.addEventListener('tsante-mqtt-connect', (evt) => {
unsubscribe: function(topic = this.topic) {

**Comment by fablec-telecomsante** [comment]
you are right, I will provide a ES5 full version.

**Comment by fablec-telecomsante** [comment]
fixed in v1.1.0

both version ES6 and ES5 are provided
