### ISSUE TITLE
The payload observer of the  publisher takes the old payload as the qos

### ISSUE THREAD

**Issue by gautaz** [telecomsante/tsante-mqtt#4]
Looking at [tsante-mqtt-publisher.js#L58](https://github.com/telecomsante/tsante-mqtt/blob/master/tsante-mqtt-publisher.js#L58), the second argument of the `publish` method should be the `qos`.

As `publish` is used as an observer of the `payload` property, the argument that is really passed is the old value of the `payload`.

**Comment by fablec-telecomsante** [comment]
Fixed in v1.1.1
