### ISSUE TITLE
Double connection fail

### ISSUE THREAD

**Issue by Billos** [telecomsante/tsante-mqtt#5]
Having the following code:
`        <tsante-mqtt id="mqtt" host="ws://{{bed.bus.url}}:{{bed.bus.port}}/" username="{{bed.bus.username}}" password="{{bed.bus.password}}"> `

The component attempts two connections, a first one without the credentials in the connectOption,
and a second one with the correct credentials. Both fail, and the client is not connected.

**Comment by fablec-telecomsante** [comment]
Modification have been done in v1.1.1 that should help to fix this pb.

Nevertheless there's a lack of explanation, did you receive "tsante-mqtt-error",  "tsante-mqtt-connect-error" events
